apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: nginx
    tier: frontend
spec:
  selector:
    matchLabels:
      tier: frontend
  replicas: 6
  template:
    metadata:
      name: nginx:1.17
      labels:
        app: nginx
        tier: frontend
    spec:
      containers:
      - name: test-nginx
        image: nginx
